make it work in source tree + error messages

diff --git a/haydenfetch b/haydenfetch
--- a/haydenfetch
+++ b/haydenfetch
@@ -1,63 +1,77 @@
-
-#!/usr/bin/env bash
+#!/bin/sh
 
 tmpfile="$(mktemp)"
 use_height=""
 hayden_directory=""
-if [ -d "/usr/share/haydenfetch/haydens" ]; then
-hayden_directory="/usr/share/haydenfetch/haydens"
-elif [ -d "/usr/local/share/haydenfetch/haydens" ]; then
-hayden_directory="/usr/local/share/haydenfetch/haydens"
-fi
+script_location=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
 while :; do
-    case "$1" in
-        "--w3m"|"w3m"|"--img"|"img"|"-i"|"i")
-            [ "$DEBUG" = "true" ] && echo "Using w3m image backend for neofetch"
-            use_w3m="true"
-            ;;
-        "--height"|"-h")
-            if [ "$use_height" = "" ]; then
-                use_height="$2"
-                [ "$DEBUG" = "true" ] && echo "Using height $height"
-            else
-                echo "You can only specify the height argument once!"
-            fi
-            ;;
-      "--haydendir")
-      hayden_directory="$2"
-      shift
- ;;
-      
-      *)
-            if [ -z "$1" ]; then
-                break
-            fi
-#            echo "Could not interpret parameter '$1'."
-            ;;
-    esac
-    shift
+	case "$1" in
+	"--w3m" | "w3m" | "--img" | "img" | "-i" | "i")
+		[ "$DEBUG" = "true" ] && echo "Using w3m image backend for neofetch"
+		use_w3m="true"
+		;;
+	"--height" | "-h")
+		if [ "$use_height" = "" ]; then
+			use_height="$2"
+			[ "$DEBUG" = "true" ] && echo "Using height $height"
+		else
+			echo "You can only specify the height argument once!"
+		fi
+		;;
+	"--haydendir")
+		hayden_directory="$2"
+		shift
+		;;
+
+	*)
+		if [ -z "$1" ]; then
+			break
+		fi
+		#            echo "Could not interpret parameter '$1'."
+		;;
+	esac
+	shift
 done
-selected_hayden=$(ls -- "$hayden_directory" | shuf -n 1)
-selected_hayden="$hayden_directory"/"$selected_hayden"
+
+# search for haydens
+if [ "$hayden_directory" != "" ]; then
+	true
+elif [ -d "./haydens" ]; then # in source tree
+	hayden_directory="$(pwd)/haydens"
+elif [ -d "/usr/share/haydenfetch/haydens" ]; then # installed via dpkg
+	hayden_directory="/usr/share/haydenfetch/haydens"
+elif [ -d "/usr/local/share/haydenfetch/haydens" ]; then # locally installed
+	hayden_directory="/usr/local/share/haydenfetch/haydens"
+fi
+
+if [ "$hayden_directory" = "" ]; then
+	echo "error: no hayden directory found. Try passing --haydendir <directory> to $(basename $0)."
+	exit 1
+fi
+selected_hayden=$(ls -- "$hayden_directory/"*.{png,jpg,jpeg,PNG,JPEG,JPG} 2> /dev/null| shuf -n 1)
+if [ "$selected_hayden" = "" ]; then
+	echo "error: no haydens found in $hayden_directory"
+	exit 2
+fi
 if [ "$use_height" != "" ]; then
-    height="$use_height"
+	height="$use_height"
 else
-    height="$(($(stty size | awk '{print $1}') - 5))"
+	height="$(($(stty size | awk '{print $1}') - 5))"
 fi
 
 if [ "$kitty_imagemagick_warn" = "true" ]; then
-        jp2a --height="$height" "$selected_hayden" > "$tmpfile"
-        neofetch --source "$tmpfile"
+	jp2a --height="$height" "$selected_hayden" >"$tmpfile"
+	neofetch --source "$tmpfile"
 elif [ "$LC_TERMINAL" = "iTerm2" ]; then
-    neofetch --iterm2 "$selected_hayden"
+	neofetch --iterm2 "$selected_hayden"
 elif [ "$use_w3m" = "true" ]; then
-    neofetch --w3m "$selected_hayden"
+	neofetch --w3m "$selected_hayden"
 else
-    jp2a --height="$height" "$selected_hayden" > "$tmpfile"
-    neofetch --source "$tmpfile"
+	jp2a --height="$height" "$selected_hayden" >"$tmpfile"
+	neofetch --source "$tmpfile"
 fi
 
 rm "$tmpfile"
 if [ "$kitty_imagemagick_warn" = "true" ]; then
-    echo "WARN: imagemagick is required for kitty image backend"
+	echo "WARN: imagemagick is required for kitty image backend"
 fi
